### ISSUE TITLE
Andverse Explorer V0.1.0 testnet Open for public testing

### ISSUE THREAD

**Issue by i29** [newtonproject/community#1]
## News title

1. Andverse Explorer V0.1.0 testnet Open for public testing.

## ECO PROJECT

1. Andverse

## Project Version
1. v0.1.0

## Content introduction （If there are format requirements, please make notes.）

Welcome to play experience and look forward to your valuable ideas and suggestions.

Links： http://play.testnet.andverse.org/

## Notes
1.
1.
1.

## Contact details
1. 
1.
1.

**Comment by i29** [comment]
@ZoeyYya is that so ?

**Comment by ZoeyYya** [comment]
Yes, it’s work. 
But Should it be written in the weekly report or Media announcement?
