### ISSUE TITLE
Newton Weekly

### ISSUE THREAD

**Issue by llc-pm** [newtonproject/community#10]
## News title
Weekly report

## ECO PROJECT
Newton

## Content introduction

Completed:

- Blockchain 
  - EVT toolchain @newton-protocol/toolchain v0.1发布 
 
Ongoing task:

- 官网
    - 修复title bug 
    - 撰写SEO优化样例 
- Newkeeper 
  - 发布 Newkeeper@v0.1.0到Github

- Blockchain 
  - Newchain web3 更新  
  - sub EVT 标准  
  - new2.0 phase#1 
    - 交易费销毁
  - 任务悬赏

**Comment by ZoeyYya** [comment]
**Date**2022.09.12—2022.09.16
**Summary** This week, the Newton community worked hard on the title repair of the official website and writing SEO optimization samples.  A better Newton community is being built, including the UI components of the Wave-Chinese version have been built, and the design is being refined at this stage.

### Core Data
- By the end of last week, there were 71 Newton human community DAOs. The amount of NEW locked-in DAOs exceeded 6.8 billion， and the number of voters 1820.
- By the end of last week, NEW had more than 1,418,076 addresses, and the NewTax had collected more than 29 million NEW.

#### Social media data：
- Twitter：7828 members
- Telegram：2749 members
- Discord：848 members
- Medium：281 followers
- Reddit：74 karma 4 years on Reddit

### Ecosystem progress
#### Newton
##### completed:
###### Blockchain
- EVT toolchain @newton-protocol/toolchain v0.1 released

##### Ongoing:
###### Website:
- fix the title bug
- Write SEO optimization samples

###### Blockchain:
- Newchain web3 update
- sub EVT standard
- New2.0 phase#1
  - Transaction fee burn

#### Wave-Chinese
##### Complected：
- UI component library construction

##### Ongoing task:
- UI-specific page design
- Movie contract design
- Official website

#### Andverse
##### Ongoing task
- Advertising space contract

### Disclaimer
Newton (NEW) is a built-in tool attribute value measurement, storage, and incentive tool for the Newton ecosystem.  Through technical infrastructure such as NewChain, a new organizational governance paradigm will be established to serve various industries and application scenarios.  Please know that the market determines its price, and the risk of drastic price fluctuations is not excluded. The content of the article does not constitute investment advice. Please make your own prudent decision and bear the corresponding risks independently.

You can learn about the latest news of Newton project through the following links:

Newton official website: [https://www.newtonproject.org](https://www.newtonproject.org/admin/zinnia/entry/2185/newtonproject.org) 

GitHub: https://github.com/newtonproject 

Twitter: https://www.twitter.com/newton_project 

Facebook: https://www.facebook.com/newtonproject

Telegram English: https://t.me/Newtonproject

Medium: https://medium.com/@newtonproject

Reddit: https://www.reddit.com/r/newton_project

Youtube: https://www.youtube.com/channel/UCO3hbqzT5abDbVKzK5EQigg 



# 中文版
**日期** 2022.09.12-2022.09.16
**总结**  这周，牛顿社区就官网的tittle 修复，撰写SEO优化样例而努力。更好的牛顿社区正在被建造，包括Wave-中文版的UI组件已建立完毕，现阶段正在就设计方面进行完善。

### 核心数据
- 截至上周末，牛顿人类社区 DAO 共有 71 个。 锁定DAO的NEW数量超过68亿，投票人数1820人。
- 截至上周末，NEW拥有超过1,418,076个地址，NewTax收集了超过2900万个NEW。

#### 社交媒体数据
- Twitter：7828名成员
- Telegram 2749 名成员
- Discord ：848 名成员
- Medium：281 名追随者
- Reddit：74 karna 4年

### 生态系统进展
#### Newton
##### 已完成：
###### Blockchain
-EVT toolchain @newton-protocol/toolchain v0.1发布

##### 正在进行:
###### Website：
- 修复title bug
-  撰写SEO优化样例

###### Blockchain：
- Newchain web3 更新
- sub EVT 标准 
- New2.0 phase#1
  - 交易费销毁

#### Wave- Chinese
##### 已完成：
-UI组件库搭建

##### 正在进行：
- UI具体页面设计
- 电影合约设计  
- 官网

#### Andverse
##### 正在进行
-	广告位合约  


### 免责声明
牛顿（NEW）是牛顿生态系统内置的工具属性值测量、存储和激励工具。 通过NewChain等技术基础设施，建立新的组织治理范式，服务于各个行业和应用场景。 请知悉，市场决定其价格，不排除价格剧烈波动的风险。 文章内容不构成投资建议。 请您自行审慎决策，并独立承担相应风险。

您可以通过以下链接了解牛顿项目的最新消息：

牛顿官网：https://www.newtonproject.org

GitHub：https://github.com/newtonproject

推特：https://www.twitter.com/newton_project

脸书：https://www.facebook.com/newtonproject

Telegram：https://t.me/Newtonproject

Medium：https://medium.com/@newtonproject

Reddit：https://www.reddit.com/r/newton_project

Youtube：https://www.youtube.com/channel/UCO3hbqzT5abDbVKzK5EQigg

## Twitter
It's time for our Weekly Report!
#Newton #Blockchain #WeeklyReport has been published.

1️⃣ What did we do last week?
2️⃣ What will we do this week?

👇Check out the latest #Newton Weekly Report! (Sept.12. 2022 to Sept.16. 2022)

#Web: （链接）
#Web3 #Metaverse
