### ISSUE TITLE
Weekly report for Newton

### ISSUE THREAD

**Issue by Jonny621** [newtonproject/community#2]
* This template is used for events, social media promotions, weekly report summaries, project update announcements and everything else that needs to be output.  *
## News title
Newton weekly report 

## ECO PROJECT
Newton

## Content introduction （If there are format requirements, please make notes.）

Completed:
1. Official website Developers module upgrade.
    link: https://www.newtonproject.org/en/developers/docs/
2. Redesign Official website Community and Ecosystem module.
3. Redefine EVTEncryption interface and extension.
    link: https://www.newtonproject.org/en/evt/
4. Update NEP-56 Region code standard.
    link: https://neps.newtonproject.org/neps/nep-56/

Ongoing task:
1. Build newton2.0 dev net.
2. Build EVT dev environment.
3. Design agreement contract interface standard.
4. Official website Community module upgrade.

**Comment by ZoeyYya** [comment]
Got it
