### ISSUE TITLE
Andverse workshop #1

### ISSUE THREAD

**Issue by i29** [newtonproject/community#4]
## News title
1.  Andverse Workshop 1:  Building scenes on Andverse

## ECO PROJECT
1. Andverse

## Project Version
1. Andverse V0.1.0 Testnet

## Content introduction （If there are format requirements, please make notes.）

Subject: 
1. Take you to the metauniverse of andverse
2. Learn about the 3D world
3. How to Build in the Andverse

## Notes
1.
1.
1.

## Contact details
1.
1.
1.

## Copy content （must******）
1.
1.
1.

##  Release Channel（choose from Twitter/Discord/Medium/Official website/Reddit/Telegram）
1.

**Comment by ZoeyYya** [comment]
## Andverse workshop#1 is coming
Let us take you into the world of the multiverse  and start your unprecedented exploration of the metaverse and blockchain.  In this workshop event, you will have the opportunity to get in touch with a 3D metaverse and discuss the construction of the metaverse with all industry insiders.

 ***Event time:*** August 28, 9:00-10:30 (UTC +4), 13:00-14:30 (UTC +8)
 Organizer: Andverse
 Twitter: @AndverseOfficial
 Website: https://www.andverse.org/ 
 How to participate: Zoom: 849 4565 8287, Password: 229898
 Free 🆓

***Rules:***
Sign up for the online sessions during the event to explore the construction of the Metaverse with industry professionals you are interested in, and let professionals guide you into the world of Andverse.  In response to social needs, the metaverse is developed to make our lives more fulfilling and beautiful, but the various problems that arise in the process cannot be solved in a short time, such as privacy issues and monopoly issues.  We are committed to exploring a more decentralized, more secure, more flexible, and more interesting metaverse.  This event invites all friends who are interested in the development of the Metaverse to join. Participants can become the first players to create "The Matrix" by themselves. Let's start your creative journey and make a money journey together.  We will introduce you to this 3D world and take you to explore the Andverse.

***The details:***
Andverse is a decentralized multigalactic world.  The Andromeda metaverse, referred to as Andverse for short, will lead different players to open a new virtual experience in the world of blockchain.  In this multiverse world—Andverse, there are infinite possibilities waiting for players to discover and explore, and Planet #3, which has been discovered at this stage, will serve as the starting point for players.  Starting from here, with our own land resources, let us build a world where consensus belongs.  Realize your architectural, design and furnishing dreams.  In this decentralized world, you can lease land, display digital collections that you own, or rent digital collections to other players for decoration.  Here, you will be able to have your own store, build your own brand, and start playing to earning.  Let's look forward to a decentralized personal ID in Andverse.  https://www.andverse.org/ 

***Participation time:***
 13:00-13:20 Experience the Andverse Metaverse
 13:20-13:40 Learn about metaverse-related technologies
 13:40-14:20 Create and deploy the scene of Andverse together
 14:20-14:30 Q&A session

 ***Kind tips:***
1.	From 23:59 on August 27th, we will close the registration window for this event, but we have prepared additional places for those who missed the registration.  They can join the meeting directly and our staff will take care of them.
2.	This event is free for everyone to participate in and is open to the public, regardless of whether they know the Metaverse or not.
3.	For users who participate in the event, if you want to know more about specific matters, please enter Telegram or follow the official Twitter to communicate with us by private message.  https://t.me/andromedametaverse 
4.	After entering the meeting, please keep the mute state. If you need to speak and then turn it on, you can selectively turn on the video mode.  Encourage everyone to actively speak, take the initiative to ask questions and discuss.


***Registration:***
Free entry for everyone, whether you are the creator of the metaverse, someone interested in digital projects or someone interested in the blockchain.  Participants please ⬇️ comment your email here.  https://github.com/andverse-core/workshop/issues/1 

***People who should be involved:***
o	Enthusiasts, owners and researchers of digital products
o	Blockchain developers
o	Those who are interested in blockchain API and DID
o	Investors and initiators of digital projects
o	People in the blockchain community
o	Defi researchers
o	Metaverse lovers




## Andverse workshop#1 is coming
让我们带你一起进入多元宇宙的世界 ，开启你对元宇宙以及区块链前所未有的探索之旅。在这次Workshop活动中，你将有机会接触到一个3D得元宇宙，和各位业内人士一起探讨元宇宙的建设。

***活动时间*** 8月28日9:00-10:30（UTC +4），13:00-14:30 （UTC +8）
组织方: Andverse
Twitter:@AndverseOfficial
Website：
参与方式: Zoom: 849 4565 8287, Password: 229898
免费🆓

***活动规则:***
报名参与活动期间的线上会议，一起和你感兴趣的业界人士探索元宇宙的建设之旅，让专业人士带领你进入 Andverse的世界。应社会需求，發展元宇宙，讓我們的生活過得更充實美好，但這過程中所衍伸的種種問題，也不是短時間內就可以解決的，像是隱私權問題、壟斷性問題等。我们将致力于探索更加去中心化的，更安全，更灵活，更有趣的的元宇宙。本活动邀请所有对元宇宙发展感兴趣的朋友加入，参与者能够成为首批自主打造“黑客帝国”的玩家，一起开启你的创作之旅和赚钱之旅吧。我们将为你介绍这个3D世界，及带你开拓Andverse。

***活动详情:***
Andverse是一个去中心化的多元宇宙世界。Andromeda metaverse简称为Andverse，它将带领不同的玩家在区块链的世界里面开启全新的虚拟体验。在这个多元宇宙的世界里，有无限种可能等待玩家去发掘和探索，现阶段被发现的Planet#3将作为玩家的出发点。从这里出发，拥有自己的土地资源，让我们一起打造一个共识所属的世界吧。实现你建筑，设计，布置的梦想。在这个自由去中心化的世界里，你可以租赁土地，可以展示个人拥有的数字藏品，也可以出租数字藏品给其他玩家作为装饰。在这里，你将可以拥有自己的店铺，打造自己的品牌，开启玩赚。让我们一起期待在Andverse里拥有一个去中心化的个人ID吧。https://www.andverse.org/ 

***参与时间:***
13:00-13:20 体验Andverse元宇宙
13:20-13:40 学习元宇宙相关技术
13:40-14:20一起创建Andverse的场景并部署场景
14:20-14:30 问答环节

***温馨提示:***
1. 自8月27日23:59起我们将全关闭此次活动的报名窗口，但我们为错过报名的朋友准备的额外的位置。他们可直接加入会议，我们的工作人员将会照顾他们。
2. 本次活动所有人均可免费参加，并向公众开放，无论是否了解元宇宙。
3. 参与活动的用户，如想了解具体事宜，请进入Telegram或者关注Twitter官方以私信的方式和我们交流。https://t.me/andromedametaverse 
4. 进入会议后，请保持静音状态，如需发言再打开，你可以有选择的开启视频模式。鼓励大家积极发言，主动提问和探讨。


***报名方式:***
所有人免费进入，无论你是区块链的创造者，对数字项目感兴趣的人还是元宇宙感兴趣的人。参与者请在这里⬇️评论你的邮箱。https://github.com/andverse-core/workshop/issues/1 

***应该参与人员:***
	数字产品的爱好者、拥有者和研究人员 
	区块链的开发者 
	对区块链API、DID感兴趣的人员 
	数字项目的投资人，发起人
	区块链社区的人员
	 Defi方向的研究人员
	元宇宙的爱好者

**Comment by ZoeyYya** [comment]
## Twitter 
#Web3, #Metaverse, #P2E? Not sure where to start? Start with us! on 28. Aug. 2022
Join our Andverse workshop – coming soon!

Just one communication will get you started on your metaverse build.
🎫Follow@AndverseOfficial
⭐️Rt & ❤️
