### ISSUE TITLE
WaveIOS更新版本

### ISSUE THREAD

**Issue by miaoruiqiang** [newtonproject/community#6]
## Wave IOS 更新版本 1.1.3
1.  提升国际化使用体验；
2.  修改已知bug；

**Comment by ZoeyYya** [comment]
# 官网公告英文

**Newton's community congratulates the Wave platform successful updated on 29/08/2022 with the following features:**

 1. The developers of wave have updated their iOS version to version 1.1.3
 2. Greatly enhances the sense of international experience.
 3. Found bugs are fixed.


 **Newton Development Team**
 **2022-08-29**
 **Thank you for your support and attention to Newton.**

# 官网公告中文
**牛顿社区祝贺 Wave 平台于 2022 年 8 月 29 日成功更新，具有以下功能：**

  1. wave开发者的iOS版本更新至1.1.3版本
  2.大大增强了国际体验感。
  3.发现的错误已修复。


  **牛顿开发团队**
  **2022-08-29**
  **感谢您对牛顿的支持和关注。**
