### ISSUE TITLE
Newton weekly report 20200905~20200909

### ISSUE THREAD

**Issue by llc-pm** [newtonproject/community#9]
## News title
Weekly report

## ECO PROJECT
Newton

## Content introduction
Completed:
官网

* 公告详情&列表页面优化

Ongoing task:
1. Developers 页面文档撰写
2. Newton-2.0-P1 交易费销毁开发
3. EVT Tutorials 完善升级

**Comment by ZoeyYya** [comment]
**Date**2022.09.05—2022.09.09
**Summary** This week, the information improvement of the official website and the page design of the Newton community were carried out.  The phased update is still in progress.


### Core Data
- By the end of last week, there were 71 Newton human community DAOs. The amount of NEW locked in DAOs exceeded 6.8 billion，and the number of voters 1820.
- By the end of last week,NEW had more than 1,418,076 addresses, the NewTax had collected more than 29 million NEW.

### Community updated

#### Social media data：
- Twitter：7568 members
- Telegram：2520 members
- Discord：533 members
- Medium：281 followers
- Reddit：74 karma 4 years on Reddit

### Ecosystem progress
#### Newton
##### Completed: 
- Announcement details and page design optimization
###### Website：
- Developers page documentation

##### Ongoing task：
###### Website
- Developers page documentation writing
###### Blockchain
- Newton-2.0-P1 transaction fee destruction development
- EVT-tutorials development
- New2.0 phase#1
 - Transaction fee burn

### Disclaimer
Newton (NEW) is a built-in tool attribute value measurement, storage, and incentive tool for the Newton ecosystem.  Through technical infrastructure such as NewChain, a new organizational governance paradigm will be established to serve various industries and application scenarios.  Please know that the market determines its price, and the risk of drastic price fluctuations is not excluded. The content of the article does not constitute investment advice. Please make your own prudent decision and bear the corresponding risks independently.

You can learn about the latest news of Newton project through the following links:

Newton official website: [https://www.newtonproject.org](https://www.newtonproject.org/admin/zinnia/entry/2185/newtonproject.org) 

GitHub: https://github.com/newtonproject 

Twitter: https://www.twitter.com/newton_project 

Facebook: https://www.facebook.com/newtonproject

Telegram English: https://t.me/Newtonproject

Medium: https://medium.com/@newtonproject

Reddit: https://www.reddit.com/r/newton_project

Youtube: https://www.youtube.com/channel/UCO3hbqzT5abDbVKzK5EQigg 



# 中文版
**日期** 2022.09.05-2022.09.09
**总结**  本周进行了官网的信息完善以及牛顿社区的页面设计。阶段型的更新，仍在进行中。


### 核心数据
- 截至上周末，牛顿人类社区 DAO 共有 71 个。 锁定DAO的NEW数量超过68亿，投票人数1820人。
- 截至上周末，NEW拥有超过1,418,076个地址，NewTax收集了超过2900万个NEW。


 ###  社区动态

#### 社交媒体数据
o	Twitter：7568名成员
o	Telegram 2520 名成员
o	Discord ：533 名成员
o	Medium：281 名追随者
o	Reddit：74 karna 4年

 ### 生态系统进展
 #### Newton
##### 已完成：
###### 官网：
- 公告详情和页面设计优化

##### 正在进行:
###### Website：
- Developers 页面文档撰写
###### Blockchain：
- Newton-2.0-P1 交易费销毁开发
- EVT tutorials开发
- New2.0 phase#1
 - 交易费
 


### 免责声明
牛顿（NEW）是牛顿生态系统内置的工具属性值测量、存储和激励工具。 通过NewChain等技术基础设施，建立新的组织治理范式，服务于各个行业和应用场景。 请知悉，市场决定其价格，不排除价格剧烈波动的风险。 文章内容不构成投资建议。 请您自行审慎决策，并独立承担相应风险。

您可以通过以下链接了解牛顿项目的最新消息：

牛顿官网：https://www.newtonproject.org

GitHub：https://github.com/newtonproject

推特：https://www.twitter.com/newton_project

脸书：https://www.facebook.com/newtonproject

Telegram：https://t.me/Newtonproject

Medium：https://medium.com/@newtonproject

Reddit：https://www.reddit.com/r/newton_project

Youtube：https://www.youtube.com/channel/UCO3hbqzT5abDbVKzK5EQigg

### Twitter
It's time for our Weekly Report!
#Newton #Blockchain #WeeklyReport has been published.

1️⃣ What did we do last week?
2️⃣ What will we do this week?
✅updated
🫶Ongoing
👇Check out the latest #Newton Weekly Report! (Step. 05, 2022 to Sept.09, 2022)

#Web: （链接）
#Web3 #Metaverse
